const sharedDimensions = (theme, { breakpoints }) => ({
  none: 'none',
  xs: '20rem',
  sm: '24rem',
  md: '28rem',
  lg: '32rem',
  xl: '36rem',
  '2xl': '42rem',
  '3xl': '48rem',
  '4xl': '56rem',
  '5xl': '64rem',
  '6xl': '72rem',
  '7xl': '80rem',
  full: '100%',
  min: 'min-content',
  max: 'max-content',
  prose: '65ch',
  100: '400px',
  200: '800px',
  300: '1200px',
  400: '1600px',
  500: '2000px',
  ...breakpoints(theme('screens')),
});

/** @type {import('tailwindcss').Config} */
/* eslint-disable no-undef */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      screens: {
        '2xl': '1440px',
        xl: '1280px',
        lg: '1024px',
        md: '768px',
        sm: '640px',
        xs: '480px',
        '2xs': '320px',
      },
      colors: {
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-on-fill': 'var(--color-text-on-fill)',
        'button-background-primary': 'var(--color-button-background-primary)',
        'button-background-primary-hover':
          'var(--color-button-background-primary-hover)',
        'button-background-primary-inverse':
          'var(--color-button-background-primary-inverse)',
        'button-background-primary-inverse-hover':
          'var(--color-button-background-primary-inverse-hover)',
        'button-background-secondary':
          'var(--color-button-background-secondary)',
        'button-background-secondary-hover':
          'var(--color-button-background-secondary-hover)',
        'button-background-danger': 'var(--color-button-background-danger)',
        'button-background-danger-hover':
          'var(--color-button-background-danger-hover)',
        'button-text-interactive': 'var(--color-button-text-interactive)',
        'button-text-interactive-on-fill':
          'var(--color-button-text-interactive-on-fill)',
        'red-text': 'var(--color-red-text)',
        'red-background-light': 'var(--color-red-background-light)',
        'red-background-dark': 'var(--color-red-background-dark)',
        'red-background-selected': 'var(--color-red-background-selected)',
        'green-text': 'var(--color-green-text)',
        'green-background-light': 'var(--color-green-background-light)',
        'green-background-dark': 'var(--color-green-background-dark)',
        'green-background-selected': 'var(--color-green-background-selected)',
        'gray-text': 'var(--color-gray-text)',
        'gray-background-light': 'var(--color-gray-background-light)',
        'gray-background-dark': 'var(--color-gray-background-dark)',
        'gray-background-selected': 'var(--color-gray-background-selected)',
        'orange-text': 'var(--color-orange-text)',
        'orange-background-light': 'var(--color-orange-background-light)',
        'orange-background-dark': 'var(--color-orange-background-dark)',
        'orange-background-selected': 'var(--color-orange-background-selected)',
        'blue-text': 'var(--color-blue-text)',
        'blue-background-light': 'var(--color-blue-background-light)',
        'blue-background-dark': 'var(--color-blue-background-dark)',
        'blue-background-selected': 'var(--color-blue-background-selected)',
        'icon-primary': 'var(--color-icon-primary)',
        'icon-secondary': 'var(--color-icon-secondary)',
        'icon-on-fill': 'var(--color-icon-on-fill)',
        'background-primary': 'var(--color-background-primary)',
        'background-primary-dark': 'var(--color-background-primary-dark)',
        'background-secondary': 'var(--color-background-secondary)',
        'background-tertiary': 'var(--color-background-tertiary)',
        'background-popover': 'var(--color-background-popover)',
        'background-blue': 'var(--color-background-blue)',
        'background-transparent': 'var(--color-background-transparent)',
        'background-hover': 'var(--color-background-hover)',
        border: 'var(--color-border)',
        overlay: 'var(--color-overlay)',
      },
      spacing: {
        0.75: '3px',
        1.25: '5px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
        40: '160px',
        48: '192px',
      },
      fontSize: {
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '30px',
        '4xl': '36px',
        '5xl': '48px',
        '6xl': '64px',
      },
      boxShadow: {
        DEFAULT:
          '0px 0px 10px 0px var(--color-gray-dark-transparent), 0px 0px 5px 0px var(--color-gray-light-transparent)',
        md: '0px 0px 15px 0px var(--color-gray-dark-transparent), 0px 0px 10px 0px var(--color-gray-light-transparent)',
        lg: '0px 0px 20px 0px var(--color-gray-dark-transparent), 0px 0px 15px 0px var(--color-gray-light-transparent)',
        xl: '0px 0px 30px 0px var(--color-gray-dark-transparent), 0px 0px 20px 0px var(--color-gray-light-transparent)',
      },
      fill: {
        current: 'currentColor',
      },
      stroke: {
        current: 'currentColor',
      },
      minHeight: {
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        full: '100%',
      },
      maxHeight: {
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
        full: '100%',
      },
      backgroundColor: (theme) => ({
        ...theme('colors'),
      }),
      backgroundImage: () => ({
        // Modify these values as per your requirement
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-linear':
          'linear-gradient(var(--tw-gradient-angle,180deg), var(--tw-gradient-stops))',
      }),
      maxWidth: sharedDimensions,
      width: sharedDimensions,
      height: sharedDimensions,
      transitionProperty: {
        none: 'none',
        all: 'all',
        DEFAULT:
          'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform',
        colors: 'background-color, border-color, color, fill, stroke',
        opacity: 'opacity',
        shadow: 'box-shadow',
        transform: 'transform',
      },
      scale: {
        0: '0',
        50: '.5',
        75: '.75',
        90: '.9',
        95: '.95',
        100: '1',
        105: '1.05',
        110: '1.1',
        125: '1.25',
        150: '1.5',
      },
      cursor: {
        auto: 'auto',
        default: 'default',
        pointer: 'pointer',
        wait: 'wait',
        text: 'text',
        move: 'move',
        'not-allowed': 'not-allowed',
      },
      borderWidth: {
        DEFAULT: '1px',
        0: '0',
        2: '2px',
        3: '3px',
        4: '4px',
        6: '6px',
        8: '8px',
      },
      borderRadius: {
        none: '0',
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        full: '9999px',
        large: '12px',
        circle: '50%',
      },
      placeholderColor: (theme) => theme('colors'),
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        linear: 'linear',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        DEFAULT: '150ms',
        75: '75ms',
        100: '100ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
      zIndex: {
        auto: 'auto',
        0: '0',
        10: '10',
        20: '20',
        30: '30',
        40: '40',
        50: '50',
        100: '100',
        menu: '1000',
      },
      animation: {
        none: 'none',
        spin: 'spin 1s linear infinite',
        ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        bounce: 'bounce 1s infinite',
      },
      keyframes: {
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
        ping: {
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
        pulse: {
          '50%': { opacity: '.5' },
        },
        bounce: {
          '0%, 100%': {
            transform: 'translateY(-25%)',
            animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
          },
          '50%': {
            transform: 'translateY(0)',
            animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
  ],
  corePlugins: {
    preflight: false,
  },
};
